# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [2388]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2389]:
A = np.arange(1, 16).reshape(3,5)

In [2390]:
print(f"Arrayen har {A.ndim} dimensioner")
print(f"Storleken på varje dimension är {A.shape}")
print(f"Totala antalet element i A är {A.size}")
print(f"Typen av element i arrayen är: {A.dtype}.")

Arrayen har 2 dimensioner
Storleken på varje dimension är (3, 5)
Totala antalet element i A är 15
Typen av element i arrayen är: int64.


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [2391]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [2392]:
print(B-C)
print()
print(B*C)
print()
print(B @ C)


[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [2393]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2394]:
#1
print(np.exp(B))
print()

#2
print(f"Minsta värdet i matrisen är {B.min()}.")
print()

#3
min_value_row = np.min(B, axis=1)
print(f"Minsta värdena i varje rad är {min_value_row}.")
print()

#4
min_value_column = np.min(B, axis=0)
print(f"Minsta värdena i varje rad är {min_value_column}.")
print()

#5
index_of_min = np.argmin(B)
print(f"Indexet för minsta värdet är {index_of_min}.")
print()

#6
index_of_min_row = np.argmin(B, axis=1)
print(f"Indexet för minsta värdet i varje rad är {index_of_min_row}.")
print()

#7
print(f"Summan av alla element är {B.sum()}.")
print()

#8
print(f"Medelvärde på varje koloumn är {np.mean(B, axis=0)}")
print()

#9
print(f"Medelvärde på varje koloumn är {np.median(B, axis=0)}")

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minsta värdet i matrisen är 1.

Minsta värdena i varje rad är [1 4 7].

Minsta värdena i varje rad är [1 2 3].

Indexet för minsta värdet är 0.

Indexet för minsta värdet i varje rad är [0 0 0].

Summan av alla element är 45.

Medelvärde på varje koloumn är [4. 5. 6.]

Medelvärde på varje koloumn är [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [2395]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [2396]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

Om man använder ett eller färre index än dimentionen på matrisen så kommer Python automatiska tänka att man vill ha allt i den dimensionen.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [2397]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [2398]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [2399]:
for element in A.flat:
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [2400]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


Med .reshape gör vi om array a till en array av tre dimensioner. Första 2:an anger att det ska bara två block och 3:an säger att det ska vara tre rader i dessa block. -1:an lämnar till python att själv räkan ut hur många element det ska vara på varje rad i blocken. I detta fall blir det 5. Vi hade alltså också kunnat skriva b = a.reshape((2, 3, 5)) och fått samma resultat.

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [2401]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])

print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [2402]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [2403]:
A = np.arange(1, 5).reshape(2,2)
print(A)
print()

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]

[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [2404]:
def add_mult_matrices(m1, m2, calculation_method):
    if not (isinstance(m1, np.ndarray) and isinstance(m2, np.ndarray)):
        print("Fel: Båda inmatningarna måste vara numpy-arrayer.")
        return
    
    if calculation_method not in ['add', 'multiply']:
        print("Fel: calculation_method måste vara antingen 'add' eller 'multiply'.")
        return
              
    if calculation_method == "add":
        if m1.shape == m2.shape:
            print("Resultat av addition:")
            print(m1 + m2)
        else:
            print("Fel: Matriserna har inte samma dimension för addition.")
    
    elif calculation_method == "multiply":
        if m1.shape[1] == m2.shape[0]:
            print("Resultat av multiplikation:")
            print(m1 @ m2)
        else:
            print("Fel: För multiplikation måste antalet kolumner i första matrisen vara lika med antalet rader i andra matrisen.")

        

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [2405]:
##10.1.1
x = np.array([4, 3])

#a dimensionen av x
print(x.ndim)
print()

#b 5x
print(5*x)
print()

#c 3x
print(3*x)
print()

#d 5x + 3x
print(5*x + 3*x)
print()

#e 8x
print(8*x)
print()

#f 4x -x
print(4*x - x)
print()

#g xT
print("Beräkna xT och nya dimensionen")
#print(x)
#print(x.T) detta fungerar inte som man tror att det skulle göra.

#x_transpose = x.reshape(1,-1).T Skapar en 2d radvektor som sedan transponeras
x_transpose = x.reshape(-1,1)   #skapar en 2d (kolumnvektor) 2D array med formen (1, n), där n är antalet element i den ursprungliga arrayen.

print(x_transpose)
print(x_transpose.ndim)

print()

#h Är x + xT definerat?
print("x + xT är inte definerat eftersom de har inte samma dimension")
#print(x + x_transpose) detta ger ett resultat (som inte borde fungera) pga broadcasting

#i ||x||
print(np.linalg.norm(x))
print()



##10.1.2
print("10.1.2")
v = np.array([[3], [7], [0], [11]])
print(v)
print()


#a dimensionen av v
print(f"vektorn v har dimensionen {v.ndim}.")
print()

#b 2v
print(2*v)
print()

#c 5v + 2v
print(5*v + 2*v)
print()

#d 4v - 2v
print(4*v - 2*v)
print()

#e vT och dimension på vT
print(v.T)
print(f"vektorn v har dimensionen {v.T.ndim}.")
print()

#f ||v||
print(np.linalg.norm(v))
print()

##10.1.3
v1 = np.array([4,3,1,5])
v2 = np.array([2,3,1,1])

print(v1, v2)

#a ||v1||
print(np.linalg.norm(v1))
print()

#b ||v1-v2||
print(np.linalg.norm(v1-v2))
print()

1

[20 15]

[12  9]

[32 24]

[32 24]

[12  9]

Beräkna xT och nya dimensionen
[[4]
 [3]]
2

x + xT är inte definerat eftersom de har inte samma dimension
5.0

10.1.2
[[ 3]
 [ 7]
 [ 0]
 [11]]

vektorn v har dimensionen 2.

[[ 6]
 [14]
 [ 0]
 [22]]

[[21]
 [49]
 [ 0]
 [77]]

[[ 6]
 [14]
 [ 0]
 [22]]

[[ 3  7  0 11]]
vektorn v har dimensionen 2.

13.379088160259652

[4 3 1 5] [2 3 1 1]
7.14142842854285

4.47213595499958



### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [2406]:
##10.2.1
A = np.array([[2,1,-1], [1,-1,1]])
B = np.array([[4,-2,1], [2,-4,-2]])
C = np.array([[1,2], [2,1]])
D = np.array([[3,4], [4,3]])
E = np.array([[1], [2]])
I = np.array([[1,0], [0,1]])


#a 2A
print(2*A)
print()

#b B-2A
print(B-2*A)
print()


#C 3C-2E
print(3*C-2*E)
print("Funkar att göra i numpy pga broadcasting men funkar inte inom vanlig matematik")
print()

Three_C = 3*C
negativ_Two_E = (-1)*2*E
add_mult_matrices(Three_C,negativ_Two_E,"add")
print()



#d 2D-3C
print(2*D-3*C)
print()

Two_D = 2*D
negativ_Three_C = (-1)*3*C
add_mult_matrices(Two_D,negativ_Three_C,"add")
print()

#e DT + 2D
D_transpose = D.T
add_mult_matrices(D_transpose,Two_D,"add")
print()

#f 2CT - 2DT
Two_C_transpose = 2*C.T
negativ_2_D_transpose = (-1)*2*D.T
add_mult_matrices(Two_C_transpose,negativ_2_D_transpose,"add")
print()

#g AT - B
A_transpose = A.T
add_mult_matrices(A_transpose,-B,"add")
print()

#h AC
add_mult_matrices(A,C,"multiply")
print()

#i CD
add_mult_matrices(C,D,"multiply")
print()

#j CB
add_mult_matrices(C,B,"multiply")
print()

#k CI
add_mult_matrices(C,I,"multiply")
print()

#l ABT
B_transpose = B.T
add_mult_matrices(A,B_transpose,"multiply")
print()


##10.2.2
print("10.2.2")
A = np.array([[2,3,4], [5,4,1]])

#Beräkna AAT
A_transpose = A.T
add_mult_matrices(A,A_transpose,"multiply")
print()


##10.2.3
print("10.2.3")
print()


A = np.array([[1,2], [2,4]])
B = np.array([[2,1], [1,3]])    
C = np.array([[4,3], [0,2]])

# AB = AC men B ≠ C
add_mult_matrices(A,B,"multiply")
print()
add_mult_matrices(A,C,"multiply")



[[ 4  2 -2]
 [ 2 -2  2]]

[[ 0 -4  3]
 [ 0 -2 -4]]

[[ 1  4]
 [ 2 -1]]
Funkar att göra i numpy pga broadcasting men funkar inte inom vanlig matematik

Fel: Matriserna har inte samma dimension för addition.

[[3 2]
 [2 3]]

Resultat av addition:
[[3 2]
 [2 3]]

Resultat av addition:
[[ 9 12]
 [12  9]]

Resultat av addition:
[[-4 -4]
 [-4 -4]]

Fel: Matriserna har inte samma dimension för addition.

Fel: För multiplikation måste antalet kolumner i första matrisen vara lika med antalet rader i andra matrisen.

Resultat av multiplikation:
[[11 10]
 [10 11]]

Resultat av multiplikation:
[[  8 -10  -3]
 [ 10  -8   0]]

Resultat av multiplikation:
[[1 2]
 [2 1]]

Resultat av multiplikation:
[[5 2]
 [7 4]]

10.2.2
Resultat av multiplikation:
[[29 26]
 [26 42]]

10.2.3

Resultat av multiplikation:
[[ 4  7]
 [ 8 14]]

Resultat av multiplikation:
[[ 4  7]
 [ 8 14]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [2407]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [2408]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [2409]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
